apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -staging

# Inject and update labels across resources, selectors, and service references
labels:
  - pairs:
      app.kubernetes.io/name: ${APPLICATION_NAME}-staging
    includeSelectors: true

images:
  - name: placeholder
    newName: ${CONTAINER_IMAGE}
    newTag: ${IMAGE_TAG}

patches:
  - path: secret-patch.yml
  - path: ingress-patch.yml
