apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinsei-manager-frontend
spec:
  template:
    spec:
      containers:
        - name: shinsei-manager-frontend
          envFrom:
            - secretRef:
                name: shinsei-manager-frontend-staging-env
