resources:
  - ../../base
  - ./ingress.yml
  - ./httproute.yml

nameSuffix: -pdf

labels:
  - pairs:
      app.kubernetes.io/name: shinsei-manager-front-pdf
    includeSelectors: true

patches:
  - path: env-patch.yml
