resources:
  - ../../base
  - ./ingress.yml

nameSuffix: -pdf

labels:
  - pairs:
      app.kubernetes.io/name: shinsei-manager-front-pdf
    includeSelectors: true

images:
  - name: placeholder
    newName: ${CONTAINER_IMAGE}
    newTag: ${IMAGE_TAG}

patches:
  - path: env-patch.yml
