stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: shinsei-manager-front
  CONTAINER_IMAGE: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}

  # Staging envs
  APPLICATION_NAME_STAGING: ${APPLICATION_NAME}-staging
  CONTAINER_IMAGE_STAGING: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME_STAGING}
  CONTAINER_IMAGE_TAGGED_STAGING: ${CONTAINER_IMAGE_STAGING}:${CI_COMMIT_SHORT_SHA}

  K8S_NODEPORT: 32725
  K8S_NODEPORT_LEGACY: 32723

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
    - when: never
  tags:
    - dind
  before_script:
    # Registry login
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_PUBLIC_URL}
    # Create repository in ECR if it does not exist yet
    - >
      aws ecr-public create-repository --region us-east-1 --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"
  script:
    # Building
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    # Pushing
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
    - when: never
  script:
    # create/update the deployment
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}

# STAGING (staging branch)

build_staging:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
    - when: never
  tags:
    - dind
  before_script:
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_PUBLIC_URL}
    - >
      aws ecr-public create-repository --region us-east-1 --repository-name ${APPLICATION_NAME_STAGING}
      || echo "Repository might have already existed"
  script:
    - docker build -t ${CONTAINER_IMAGE_TAGGED_STAGING} .
    - docker push ${CONTAINER_IMAGE_TAGGED_STAGING}

deploy_staging:
  stage: deploy
  needs:
    - build_staging
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
    - when: never
  tags:
    - dind
  script:
    - envsubst < kubernetes_manifest_staging.yml | kubectl apply -f -
     # Validate deployment rollout status
    - kubectl rollout status deployment/$APPLICATION_NAME_STAGING --timeout=600s
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}