stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: shinsei-manager-front
  SERVICE_PORT: 32723

containerization:
  stage: containerization
  script:
    - cp ${ENV} ./.env.production
    - >
      docker build
      --build-arg HTTP_PROXY=$HTTP_PROXY
      --build-arg HTTPS_PROXY=$HTTPS_PROXY
      -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
      .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME} # Cleanup

deployment:
  stage: deployment
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
