stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: shinsei-manager-front
  CONTAINER_IMAGE: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME}

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: ${CI_COMMIT_TAG}
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
    - when: never
  tags:
    - dind
  before_script:
    - aws ecr-public create-repository --repository-name ${APPLICATION_NAME} || echo "Repository might have already existed"
  script:
    - docker build -t ${CONTAINER_IMAGE}:${IMAGE_TAG} .
    - docker push ${CONTAINER_IMAGE}:${IMAGE_TAG}

deploy:
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        ENVIRONMENT: prod
        IMAGE_TAG: ${CI_COMMIT_TAG}
        NAME_SUFFIX: ""
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        ENVIRONMENT: staging
        IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
        NAME_SUFFIX: -staging
    - when: never
  script:
    - kubectl kustomize kustomize/overlays/${ENVIRONMENT} | envsubst | kubectl apply -f -
    - kubectl kustomize kustomize/overlays/pdf-${ENVIRONMENT} | envsubst | kubectl apply -f -
    - kubectl rollout status deployment/${APPLICATION_NAME}${NAME_SUFFIX} --timeout=600s
    - kubectl rollout status deployment/${APPLICATION_NAME}-pdf${NAME_SUFFIX} --timeout=600s
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
