apiVersion: apps/v1
kind: Deployment
metadata:
    name: shinsei-manager-front
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shinsei-manager-front
    template:
        metadata:
            labels:
                app: shinsei-manager-front
        spec:
            containers:
                - name: shinsei-manager-front
                  image: ${CONTAINER_IMAGE_TAGGED}
                  ports:
                      - containerPort: 80
                  envFrom:
                      - secretRef:
                            name: environment-variables
---
apiVersion: v1
kind: Service
metadata:
    name: shinsei-manager-front
spec:
    type: NodePort
    selector:
        app: shinsei-manager-front
    ports:
        - port: 80
          nodePort: 32725
---
# Secondary service to account for legacy version
apiVersion: v1
kind: Service
metadata:
    name: shinsei-manager-front-legacy
spec:
    type: NodePort
    selector:
        app: shinsei-manager-front
    ports:
        - port: 80
          nodePort: 32723
