/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/About': RouteRecordInfo<
      '/About',
      '/About',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/Application': RouteRecordInfo<
      '/Application',
      '/Application',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/ApplicationList': RouteRecordInfo<
      '/ApplicationList',
      '/ApplicationList',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/Login': RouteRecordInfo<
      '/Login',
      '/Login',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/NewApplication': RouteRecordInfo<
      '/NewApplication',
      '/NewApplication',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/NewTemplate': RouteRecordInfo<
      '/NewTemplate',
      '/NewTemplate',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/NotFound': RouteRecordInfo<
      '/NotFound',
      '/NotFound',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/OidcCallback': RouteRecordInfo<
      '/OidcCallback',
      '/OidcCallback',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/PasswordReset': RouteRecordInfo<
      '/PasswordReset',
      '/PasswordReset',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/Search': RouteRecordInfo<
      '/Search',
      '/Search',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/Template': RouteRecordInfo<
      '/Template',
      '/Template',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/TemplateList': RouteRecordInfo<
      '/TemplateList',
      '/TemplateList',
      Record<never, never>,
      Record<never, never>,
      never
    >
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/About.vue': {
      routes: '/About'
      views: never
    }
    'src/pages/Application.vue': {
      routes: '/Application'
      views: never
    }
    'src/pages/ApplicationList.vue': {
      routes: '/ApplicationList'
      views: never
    }
    'src/pages/Login.vue': {
      routes: '/Login'
      views: never
    }
    'src/pages/NewApplication.vue': {
      routes: '/NewApplication'
      views: never
    }
    'src/pages/NewTemplate.vue': {
      routes: '/NewTemplate'
      views: never
    }
    'src/pages/NotFound.vue': {
      routes: '/NotFound'
      views: never
    }
    'src/pages/OidcCallback.vue': {
      routes: '/OidcCallback'
      views: never
    }
    'src/pages/PasswordReset.vue': {
      routes: '/PasswordReset'
      views: never
    }
    'src/pages/Search.vue': {
      routes: '/Search'
      views: never
    }
    'src/pages/Template.vue': {
      routes: '/Template'
      views: never
    }
    'src/pages/TemplateList.vue': {
      routes: '/TemplateList'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
