apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/name: ${APPLICATION_NAME}
    includeSelectors: true

images:
  - name: placeholder
    newName: ${CONTAINER_IMAGE}
    newTag: ${IMAGE_TAG}
