apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_IMAGE}:1.6.3
        #imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Get environment variables from secret
        envFrom:
        - secretRef:
           name: environment-variables
