/**
 * Environment variables, merging Vite's build-time `import.meta.env` with
 * `window.__ENV__`, a config object generated by 40-env-config.sh at
 * container start (see /env.js). Runtime values take precedence so the same
 * build can be deployed to different environments without a rebuild.
 */

const runtimeEnv = {
  ...import.meta.env,
  ...window.__ENV__,
}

export default runtimeEnv
